# Promotion target for the dev stage. Kargo updates image.tag and env.LAMBDA_URL.
stage: dev
replicaCount: 1
image:
  tag: 6
env:
  LAMBDA_URL: https://kv6tedzmrerzqz43oqj7ewivte0irlql.lambda-url.us-east-1.on.aws/
